version: '3.8'

services:
  # Nginx web server
  web:
    image: nginx:alpine
    container_name: sourdough-web
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
    restart: always
