version: '3.8'

services:
  # API server
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: sourdough-api
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - ./server/data:/app/data
    restart: always
    networks:
      - sourdough-network

  # Nginx web server
  web:
    image: nginx:alpine
    container_name: sourdough-web
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    restart: always
    networks:
      - sourdough-network

networks:
  sourdough-network:
    driver: bridge
